version: '3.8'

services:
  app:
    build:
      context: ./docker/php
    container_name: meatmanufature_app
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - meatmanufature
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: meatmanufature_nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - meatmanufature

  db:
    image: postgres:16
    container_name: meatmanufature_db
    environment:
      POSTGRES_DB: meatmanufature
      POSTGRES_USER: meatmanufature
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - meatmanufature

networks:
  meatmanufature:

volumes:
  pgdata:
